[package]
  cjc-version = "1.0.0"
  name = "cli"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  magic = { path = "./CangjieMagic" }

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["./CangjieMagic/libs/cangjie-stdx-windows-x64-1.0.0.1/windows_x86_64_llvm/dynamic/stdx"]
